name: Deploy Infra

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TOFU_VERSION: 1.8.2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Infra Repo
      uses: actions/checkout@v3

    # --- Configure AWS Credentials using OIDC ---
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::311601977586:role/GitHubActionsDeployRole
        aws-region: ${{ env.AWS_REGION }}

    # --- Install OpenTofu ---
    - name: Install OpenTofu
      run: |
        curl -LO https://github.com/opentofu/opentofu/releases/download/v${{ env.TOFU_VERSION }}/tofu_${{ env.TOFU_VERSION }}_linux_amd64.zip
        unzip tofu_${{ env.TOFU_VERSION }}_linux_amd64.zip -d /usr/local/bin/
        tofu version

    # --- Terraform Init ---
    - name: Init OpenTofu
      run: |
        tofu init

    # --- Terraform Plan ---
    - name: Plan
      run: |
        tofu plan -out=tfplan

    # --- Terraform Apply ---
    - name: Apply
      if: github.ref == 'refs/heads/main'
      run: |
        tofu apply -auto-approve tfplan
